# Generated by Django 4.1.7 on 2023-04-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='full_name',
            new_name='username',
        ),
    ]
